spring:
    profiles: default
    application:
        name: application-registry
security:
    user:
        password: bebgb58b45ufb84h4tfb8bs74yytg59p0u0iuf584fbriufn48f4nf7                 
server:
    port: 8081
    context-path: /registry
    address: localhost
eureka:
    instance:
        protocol: http
        ip-address: localhost
        port: 8081
        hostname: localhost
        context-path: /registry
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: ${eureka.instance.protocol}://${eureka.instance.ip-address}:${eureka.instance.port}${eureka.instance.context-path}/eureka/
        register-with-eureka: false
        fetch-registry: false
management:
    context-path: /admin