spring:
    profiles: default
    application:
        name: registry
security:
    user:
        password: bebgb58b45ufb84h4tfb8bs74yytg59p0u0iuf584fbriufn48f4nf7                 
server:
    port: 8081
    context-path: /registry
    address: localhost

---
spring:
    profiles:
        active: default