spring:
    profiles: default
    application:
        name: application-gateway
security:
    user:
        password: bebgb58b45ufb84h4tfb8bs74yytg59p0u0iuf584fbriufn48f4nf7                 
server:
    port: 80
    context-path: /gateway
    address: localhost
eureka:
    instance:
        protocol: http
        ip-address: localhost
        port: 8081
        hostname: localhost
        context-path: /registry
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: ${eureka.instance.protocol}://${eureka.instance.ip-address}:${eureka.instance.port}${eureka.instance.context-path}/eureka/
zuul:
    routes:
        registrys:
            path: /registry/**
            retryable: true
            sensitive-headers:
            strip-prefix: false
        account:
            path: /account/**
            retryable: true
            strip-prefix: false
        gateway:
            path: /gateway/**
            retryable: true
            strip-prefix: false
    add-proxy-headers: true