spring:
    profiles: production
    application:
        name: application-registry
    aop:
        proxy-target-class: true
security:
    user:
        password: bebgb58b45ufb84h4tfb8bs74yytg59p0u0iuf584fbriufn48f4nf7                 
server:
    port: 8081
    context-path: /registry
    address: 0.0.0.0
eureka:
    instance:
        protocol: http
        ip-address: 172.17.0.1
        port: 8081
        context-path: /registry
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: ${eureka.instance.protocol}://${eureka.instance.ip-address}:${eureka.instance.port}${eureka.instance.context-path}/eureka/
        register-with-eureka: false
        fetch-registry: false
management:
    context-path: /admin